### ISSUE TITLE
The Data Remaining doesnt decrease

### ISSUE THREAD

**Issue by Doimatcuabautroi** [TheCaduceus/WARP-UNLIMITED-ADVANCED#1]
Hello, I have follow up your instruction to get unlimited data, but look like sometimes it doesnt work correctly.
First, I ran your script on google colab and data was increase, after that i reset encrypt key on IOS, It worked but I usually recheck the data after 30' that I search web, tiktok, fb, ... and see that the data will be decrease in a "random time".
It also doesnt work on Windows, I copied the license key on IOS and pasted on PC, I also rechecked like I did on IOS, I re-enter the license key on WARP Windows, but the data nerver decrease one time.
Please check again, thank you.

**Comment by TheCaduceus** [comment]
> Hello, I have follow up your instruction to get unlimited data, but look like sometimes it doesnt work correctly. First, I ran your script on google colab and data was increase, after that i reset encrypt key on IOS, It worked but I usually recheck the data after 30' that I search web, tiktok, fb, ... and see that the data will be decrease in a "random time". It also doesnt work on Windows, I copied the license key on IOS and pasted on PC, I also rechecked like I did on IOS, I re-enter the license key on WARP Windows, but the data nerver decrease one time. Please check again, thank you.

Thanks! For reaching out to me. I will look into the matter and update you!

**Comment by TheCaduceus** [comment]
> Hello, I have follow up your instruction to get unlimited data, but look like sometimes it doesnt work correctly. First, I ran your script on google colab and data was increase, after that i reset encrypt key on IOS, It worked but I usually recheck the data after 30' that I search web, tiktok, fb, ... and see that the data will be decrease in a "random time". It also doesnt work on Windows, I copied the license key on IOS and pasted on PC, I also rechecked like I did on IOS, I re-enter the license key on WARP Windows, but the data nerver decrease one time. Please check again, thank you.

Just for your Information! Keys from iOS update the Values only in Apple's Ecosystem. You have to use Android phone in that case.

**Comment by Doimatcuabautroi** [comment]
I reset "all setting" Warp on Win, that time warp on win had a new license, Next, I used your script to upgrade on Warp+, then copied the licence key on Win to IOS, unlucky, it doesnt work ._, . Look like, only Android phone can share the data with many device. But i dont understand that the licence key could be use by 5 devices, IOS to WIN doesnt work, WIN to IOS doesnt work too. I dont have android phone 👎. BTW, althought the data remaining on Win (which copied from IOS) doesnt decrease, but I have a question, Does WARP+ on Win still have benefit from WARP+ while the data remaining not decrease ?

**Comment by TheCaduceus** [comment]
> I reset "all setting" Warp on Win, that time warp on win had a new license, Next, I used your script to upgrade on Warp+, then copied the licence key on Win to IOS, unlucky, it doesnt work ._, . Look like, only Android phone can share the data with many device. But i dont understand that the licence key could be use by 5 devices, IOS to WIN doesnt work, WIN to IOS doesnt work too. I dont have android phone 👎. BTW, althought the data remaining on Win (which copied from IOS) doesnt decrease, but I have a question, Does WARP+ on Win still have benefit from WARP+ while the data remaining not decrease ?
Just to make things cleared! You can use Activation Key from Android to Windows or Linux! But not from iOS and yes WARP+ have benefit from Normal WARP

**Comment by Doimatcuabautroi** [comment]
Can I use activation key from Android to IOS ?

**Comment by TheCaduceus** [comment]
> Can I use activation key from Android to IOS ?
---
I am not confirmed yet, but probably No.
