### ISSUE TITLE
add koyeb and goorm support

### ISSUE THREAD

**Issue by rmf2** [TheCaduceus/WARP-UNLIMITED-ADVANCED#14]
for that heroku would cancel its free service,and railway restrict its used , koyeb and goorm would be highly recommanded.
here  
koyeb.com
goorm.io

**Comment by TheCaduceus** [comment]
@ravindusha For Koyeb, use Docker Image to deploy `ghcr.io/thecaduceus/wla:master` and for goorm it will involve the same steps which is written for VPS.

**Comment by TheCaduceus** [comment]
@rmf2 Added koyeb one click deployment button! have a look on it.
