### ISSUE TITLE
Problems on "Run on Mobile Phone"

### ISSUE THREAD

**Issue by SamadXYZ** [TheCaduceus/WARP-UNLIMITED-ADVANCED#42]
![Screenshot_20230111-115822_Termux](https://user-images.githubusercontent.com/98101010/211730541-d6ddfdcd-741e-42af-a731-066c1237c669.jpg)
What to do ?

**Comment by TheCaduceus** [comment]
@SamadXYZ You forgot to run following command after `git clone`:
```
cd WARP-UNLIMITED-ADVANCED
```
