### ISSUE TITLE
I got FAILED error message while running the notebook on Google Colab

### ISSUE THREAD

**Issue by DEA-Raison** [TheCaduceus/WARP-UNLIMITED-ADVANCED#51]
Here is the error log

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting httpx
  Downloading httpx-0.24.0-py3-none-any.whl (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.3/75.3 kB 1.4 MB/s eta 0:00:00
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from httpx) (2022.12.7)
Collecting httpcore<0.18.0,>=0.15.0
  Downloading httpcore-0.17.0-py3-none-any.whl (70 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.6/70.6 kB 5.7 MB/s eta 0:00:00
Requirement already satisfied: sniffio in /usr/local/lib/python3.10/dist-packages (from httpx) (1.3.0)
Requirement already satisfied: idna in /usr/local/lib/python3.10/dist-packages (from httpx) (3.4)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.10/dist-packages (from httpcore<0.18.0,>=0.15.0->httpx) (3.6.2)
Collecting h11<0.15,>=0.13
  Downloading h11-0.14.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 1.8 MB/s eta 0:00:00
Installing collected packages: h11, httpcore, httpx
Successfully installed h11-0.14.0 httpcore-0.17.0 httpx-0.24.0
FAILED: 429
Sleep: 33 seconds.

**Comment by TheCaduceus** [comment]
Read FAQ.
