### ISSUE TITLE
HTTP/1.1 500

### ISSUE THREAD

**Issue by Hipoglos** [TheCaduceus/WARP-UNLIMITED-ADVANCED#53]
[12/06/2023 06:36:05][INFO] => HTTP Request: POST https://api.cloudflareclient.com/v0a821/reg "HTTP/1.1 500 Internal Server Error"
[12/06/2023 06:36:05][INFO] => FAILED: 500

Is this script still working?

**Comment by TheCaduceus** [comment]
Refer to ISSUE #52

**Comment by Hipoglos** [comment]
Thanks @TheCaduceus, but the status api webpage shows it's up.

**Comment by TheCaduceus** [comment]
**Read this comment:**
https://github.com/TheCaduceus/WARP-UNLIMITED-ADVANCED/issues/52#issuecomment-1551135615

**Comment by Hipoglos** [comment]
Worked! Thanks and sorry for not being able to even read correctly!
