### ISSUE TITLE
Vps installation 

### ISSUE THREAD

**Issue by arjung24** [TheCaduceus/WARP-UNLIMITED-ADVANCED#55]
I was trying to install warp unlimited on oracle vps. But i am facing problem when executing last command
py warp-plus.py

Please help

![IMG_20230625_184729](https://github.com/TheCaduceus/WARP-UNLIMITED-ADVANCED/assets/68998000/2a1869d5-7989-4386-8972-630dc64fe6c0)

**Comment by TheCaduceus** [comment]
Use `python` or `python3` instead of `py`, this error is from installation process.

**Comment by arjung24** [comment]
> Use `python` or `python3` instead of `py`, this error is from installation process.

I did with python3. But how can i check my vps running with warp unlimited 

![IMG_20230625_205539](https://github.com/TheCaduceus/WARP-UNLIMITED-ADVANCED/assets/68998000/096bc84a-7513-4d8d-b12c-58715a1a698c)

**Comment by TheCaduceus** [comment]
In config.py change line 34, put `False` between "".
https://github.com/TheCaduceus/WARP-UNLIMITED-ADVANCED/blob/342f0249643f248b60fcce10647296588d796ce4/config.py#L34

**Comment by arjung24** [comment]
> In config.py change line 34, put `False` between "".
> 
> https://github.com/TheCaduceus/WARP-UNLIMITED-ADVANCED/blob/342f0249643f248b60fcce10647296588d796ce4/config.py#L34

![IMG_20230625_230605](https://github.com/TheCaduceus/WARP-UNLIMITED-ADVANCED/assets/68998000/3288f262-4366-4199-9ba2-06e372dab67f)
