### ISSUE TITLE
not opening file in cmd

### ISSUE THREAD

**Issue by ragnar-git** [TheCaduceus/WARP-UNLIMITED-ADVANCED#7]
i am using your cmd with telegram log enable script. I follow all your steps but when i open that warp.py file it not opening.when i try to open that file then command prompt opens and close automatically in 1 second

**Comment by TheCaduceus** [comment]
@ragnar-git Thanks for report! This project not get update from long time! I will update it.

**Comment by TheCaduceus** [comment]
@ragnar-git This problem is now resolved in latest version!
